REQUIRED_PAYLOAD_FIELDS = [
    "user",
    "recipient",
    "creation_at",
    "expires_at",
    "data",
    "verification",
    "signature",
]
COLLECTION_PAYLOADS = "payloads"
COLLECTION_REQUESTS = "requests"
COLLECTION_REQUEST_DECISIONS = "request_decisions_v1"
COLLECTION_RATE_LIMITS = "rate_limits_v1"

DEFAULT_DOCUMENT_TTL_SECONDS = 60 * 60 * 24 * 7
MAX_DOCUMENT_TTL_SECONDS = 60 * 60 * 24 * 14
MAX_CLOCK_SKEW_SECONDS = 5 * 60
MAX_FETCH_LIMIT = 200
DEFAULT_FETCH_LIMIT = 100
MAX_DATA_B64_LENGTH = 128 * 1024
MAX_SIGNATURE_B64_LENGTH = 1024
MAX_VERIFICATION_B64_LENGTH = 512
MAX_REQUEST_ID_LENGTH = 128
DEFAULT_SCHEMA_VERSION = 1
DECISION_COMPAT_DEPRECATION_DATE = "2026-07-31"
RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_UPLOAD_PER_WINDOW = 60
RATE_LIMIT_FETCH_PER_WINDOW = 120
RATE_LIMIT_DECISION_PER_WINDOW = 60

DEFAULT_SCHEDULER_SERVICE_ACCOUNT_EMAIL = "expiration-cleanup-scheduler@shary-21b61.iam.gserviceaccount.com"
